

function T_matrix=FDM_2D_3D_transient_TapeANDSub_combined(Lx,Ly,Lz,xnode,ynode,znode,E_points,v_original,materials,Temp_Incoming,h,Temp_Conv_inside,...
    Rel_v_theta,Measure_Box_Sub,fileID_Temp_Red_Box,Tecplot_check,Graphic_profile,Grpahic_contour,...
    Live_output,init_Temp,Inc_transient,Time_transient,...
    Lx_T,Ly_T,xnode_T,ynode_T,E_points_T,v_original_T,materials_T,Temp_Right_T_Roller,h_T,thickness_T,...
    Row_number_Tape_Roller_tangent_T,Measure_Box_Tape_T,fileID_Temp_Red_Box_T,Graphic_Profile_T,Graphic_contour_T,Tecplot_check_T,...
    Power_Tank,video_ID,manufacturing_type,W_R,R_tape,...
    text_status,nonlinearMaterials_Tape_Sub)



%% should be revised for Layer_number >1     >>>>>>>>>>> 31 Dec 2019

% Ly is the half width of substrate
if isempty(nonlinearMaterials_Tape_Sub)
Non_lin_thermal=0;
