
% This program is able to calculate and combine of two axis systems to
%Transformation of rays and intersection points should be into axis-1 which

% Calculate for 1st reflection


function [counter_ray,Rot_Roller_axis,tv]=General_3D_Optical_UOT(th_y,Tape_Sp,...
    Rxyz,R_cyl,z_cyl_end,Roller_Pos_TV,ID,Laser_head,absorbtion_waste,W_R,H_indentation,...
    Graphic_chekbox,...
    BRDF_mode,jobname,...
    CV_mesh,LaserH_mesh,delta_new_all,pos_new_all,nip_point_M_all,Rot_Roller_axis_all,...
    UOT_pathfile,text_status,Divergence_factor)
