function [VarName1,VarName2] = importfile_Inputs_Excel(workbookFile,sheetName,startRow,endRow,startCol,endCol)
%IMPORTFILE Import data from a spreadsheet
%   [VarName1,VarName2] = IMPORTFILE(FILE) reads data from the first
%   worksheet in the Microsoft Excel spreadsheet file named FILE and
%   returns the data as column vectors.
%
%   [VarName1,VarName2] = IMPORTFILE(FILE,SHEET) reads from the specified
%   worksheet.
%
%   [VarName1,VarName2] = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from
%   the specified worksheet for the specified row interval(s). Specify
%   STARTROW and ENDROW as a pair of scalars or vectors of matching size
%   for dis-contiguous row intervals. To read to the end of the file
%   specify an ENDROW of inf.%
% Example:
%   [VarName1,VarName2] = importfile('inputs-velocity-power-HDPE.xlsx','Sheet1',1,184117);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2018/06/26 11:48:12

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 176500;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('%s%d:%s%d',startCol(1),startRow(1),endCol(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('%s%d:%s%d',startCol(1),startRow(block),endCol(1),endRow(block) ));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2]);

%% Allocate imported array to column variable names
VarName1 = cellVectors(:,1);
VarName2 = cellVectors(:,2);

