
%%
% Last modification: 26 March 2018
%  fix long substrate length, in-out surface
% Temperature of the mandrel contact with substrate


%%
%  >>>>>>>>>>>> Changed on 5 April 2019  >> Not verfied !!!!!!!!!
%  <<<<<




function Inline_thermal_domain_generator_Tr(th_y,W_tape,thick_T,R_tape,L_flat,deg_tape,...
    sui,L_prim,No_dev_L ,w,thick_sub,No_dev,R_cyl,z_cyl_end,...
    tv3,W_R,materials_Tape,materials_sub,...
    Rxyz,ID,Laser_head,L_xyz0,absorbtion_waste,...
    node_space,Angular_space,L_flat_space,...
    Temp_Right_sub,Temp_Right_T_Roller,h_conv_Sub,h_conv_T,H_indentation,Node_z_3D_thermal,T_amb_mandrel,....
           Graphic_chekbox,Inline_ID,manufacturing_type,Laser_head_Rot,...
           ADS_Vars,TwinCat_file_name,...
           BRDF_mode,Divergence_factor)
