%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: M:\PhD-works\Programming\Advection-diffusion\FDM_transient\Nonlinear material\Material_model.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/05/18 09:50:35

%% Import the data
% non-constant
[~, ~, raw] = xlsread('M:\PhD-works\Programming\Advection-diffusion\FDM_transient\Nonlinear material\Material_model.xlsx','Sheet1','D7:H16');

% Constant
% [~, ~, raw] = xlsread('M:\PhD-works\Programming\Advection-diffusion\FDM_transient\Nonlinear material\Material_model.xlsx','Sheet2','D7:H16');


raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Temperature = data(:,1);
specificheat = data(:,2);
Density = data(:,3);
ThermalconductivityAxial = data(:,4);
Thermalconductivitytransverse = data(:,5);

%% Clear temporary variables
clearvars data raw R;